spring:
  application:
    name: hello-service
  datasource:
    url: jdbc:mysql://localhost:3306/fun_funwork?useSSL=false&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
mybatis:
  type-aliases-package: com.daka.client.dao
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
#  - com.daka.client.config.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql